# Generated by Django 4.1 on 2022-11-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notehub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="upload_time",
            field=models.DateTimeField(auto_now_add=True, default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="uploader",
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
