# Generated by Django 4.1 on 2022-11-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notehub", "0002_note_upload_time_note_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="upload_time",
            field=models.CharField(max_length=32),
        ),
    ]
