# Generated by Django 4.1 on 2022-11-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notehub", "0003_alter_note_upload_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="upload_time",),
    ]
