# Generated by Django 4.1 on 2022-11-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notehub", "0004_remove_note_upload_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="uploader",),
    ]
